name: pass_emploi_app
description: Pass Emploi iOS and Android app.

publish_to: "none"
version: 3.7.0

environment:
  sdk: 3.2.0 # Dart version
  flutter: 3.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Dart
  intl: "0.18.1"
  collection: "1.18.0"
  equatable: "2.0.5"
  synchronized: "3.1.0"
  uuid: "3.0.7"
  clock: "1.1.1"
  # Dio
  dio: "5.3.4"
  dio_cache_interceptor: "3.4.4"
  dio_cache_interceptor_file_store: "1.2.2"
  # Firebase
  firebase_core: "2.23.0"
  firebase_crashlytics: "3.4.5"
  firebase_remote_config: "4.3.5"
  firebase_messaging: "14.7.5"
  firebase_auth: "4.14.1"
  firebase_app_installations: "0.2.4+5"
  cloud_firestore: "4.13.2"
  # UI
  flutter_svg: "2.0.9"
  smooth_page_indicator: "1.1.0"
  path_provider: "2.1.1"
  flutter_staggered_animations: "1.1.1"
  shimmer: "3.0.0"
  confetti: "0.7.0"
  dotted_border: "2.1.0"
  flutter_linkify: "6.0.0"
  # Native features
  webview_flutter: "4.4.2"
  flutter_local_notifications: "16.1.0"
  flutter_appauth: "6.0.2"
  flutter_secure_storage: "9.0.0"
  url_launcher: "6.2.1"
  share_plus: "7.2.1"
  open_filex: "4.3.4"
  in_app_review: "2.0.8"
  flutter_native_timezone: "2.0.0"
  connectivity_plus: "4.0.2" # Versions >= 5.0.0 require iOS 12 or higher
  # Others
  flutter_redux: "0.10.0"
  redux: "5.0.0"
  flutter_dotenv: "5.1.0"
  package_info: "2.0.2"
  encrypt: "5.0.3"
  matomo_tracker: "4.1.1"
  logger: "2.0.2+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "0.13.1"
  flutter_lints: "3.0.1"
  mocktail: "1.0.1"
  flutter_native_splash: "2.3.6"
  http_mock_adapter: "0.6.0"

dependency_overrides:
  http: "1.1.0"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tuto/
    - assets/mode_demo/
    - assets/mode_demo/brsa/
    - assets/mode_demo/cej/
    - env/

  fonts:
    - family: AppIconsAdditional
      fonts:
        - asset: fonts/AppIconsAdditional.ttf
    - family: Marianne
      fonts:
        - asset: fonts/Marianne-Regular.otf
        - asset: fonts/Marianne-Regular.otf
          weight: 400
        - asset: fonts/Marianne-Bold.otf
          weight: 700
