name: Release - Mobile App

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
      - name: Lancer les tests
        run: flutter test

  pre-build:
    runs-on: ubuntu-latest
    needs: test
    name: pre-build
    steps:
      - name: Get current timestamp
        id: getCurrentTimestamp
        run: echo "::set-output name=date::$(date +%s)"
    outputs:
      date: ${{ steps.getCurrentTimestamp.outputs.date }}


  build-android-prod:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'

      - name: Write Google configuration for Android
        shell: bash
        run: |
          mkdir android/app/src/prod
          echo "$PROD_GOOGLE_SERVICE_B64" | base64 --decode > android/app/src/prod/google-services.json
        env:
          PROD_GOOGLE_SERVICE_B64: ${{ secrets.PROD_GOOGLE_SERVICE_B64 }}

      - name: Write key properties
        shell: bash
        run: |
          echo "$KEY_PROPERTIES_B64" | base64 --decode > android/key.properties
        env:
          KEY_PROPERTIES_B64: ${{ secrets.KEY_PROPERTIES_B64 }}

      - name: Write key store
        shell: bash
        run: |
          mkdir android/keystore
          echo "$KEYSTORE_B64" | base64 --decode > android/keystore/passemploi.jks
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}

      - name: Write env
        shell: bash
        run: |
          echo "$PROD_RUNTIME_ENV_B64" | base64 --decode > env/.env.prod
        env:
          PROD_RUNTIME_ENV_B64: ${{ secrets.PROD_RUNTIME_ENV_B64 }}

      - name: Build Android appbundle
        run: |
          flutter pub get
          flutter build appbundle \
          --flavor prod \
          --build-number=${{ needs.pre-build.outputs.date }}


      - name: Deploy Android appbundle
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PROD_GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: fr.fabrique.social.gouv.passemploi
          releaseFiles: build/app/outputs/bundle/prodRelease/app-prod-release.aab
          track: internal
          status: completed
